# Generated by Django 5.2.13 on 2026-05-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_github_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='pan_number',
        ),
    ]
