# Generated by Django 5.2.13 on 2026-05-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customerprofile_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='users_resumes/'),
        ),
    ]
