# Generated by Django 5.2.13 on 2026-05-02 17:59

import apps.accounts.models.user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customerprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=apps.accounts.models.user_model.user_resume_path),
        ),
    ]
